### ISSUE TITLE
?dequip {equipment_id (-s)}

### ISSUE THREAD

**Issue by Profmash** [carsakiller/Carsas-Commands#1]
**Is your feature request related to a problem? Please describe.**
-To dequip some things I have to spawn an outfit and tool locker and put things there. This command will work like ?equip {equipment_id (-s)} but it will remove things from inventory.
**Describe the feature you'd like**
-Players will be able to get rid of equipment without seeing a it dropped on ground in future.

**Comment by carsakiller** [comment]
This could be a nice addition to the script. Something like `?dequip 0 2` (_dequip player 0 in slot 2_) could work. Thoughts?
