### ISSUE TITLE
Vehicle Spawn List

### ISSUE THREAD

**Issue by EndoSkull** [carsakiller/Carsas-Commands#3]
Is it possible to create a script addon that allows for a list of vehicles to be spawned per request in chat.
To use the script you would likely need to have us create a vehicle spwn list using locations in the mission editor. And add one for each vehicle - then add an id for each one in your Server Commands Script.
Too bad I suck at scripting :-P

Example Chat:

Endo>?air
Server>Please provide ID: 1 = Piper Cub 2 = Water Hopper 3 = Passenger Plane
Endo>?air 1
Server>Spawning Piper Cub at Harris Airfield

**Comment by carsakiller** [comment]
Hey Endo,

I think it would be too much to add to _Carsa's Commands_ but it could be a good idea, like you said, for a different script. I think this could be a helpful script but I would need to know more about the idea before starting development. I still have many questions and would like to know how you would like to see certain things implemented. If you'd like, you can DM me on Discord at `Carsakiller#5659`
